### ISSUE TITLE
No info after plugin is installed

### ISSUE THREAD

**Issue by masterwishx** [cloudflare/cloudflare-grafana-app#52] opened 2021-12-21 17:44 UTC
After installed plugin in grafana 
No dashboards  in Cloudflare APP founded but they apper in General Folder but only one info working all other info forbiden 

![image](https://user-images.githubusercontent.com/28630321/146974326-04a76994-1038-4c88-bc4f-df8967961c48.png)
![image](https://user-images.githubusercontent.com/28630321/146974793-cc84ad5b-723d-4a4f-bc27-a442db9c3b3d.png)
![image](https://user-images.githubusercontent.com/28630321/146974932-a76d56b6-3668-45d1-8662-ac7540102098.png)

is the APP not for Free Plan Cloudflare ?

**Comment by ersefa** [comment] 2022-01-13 14:12
same here with a business plan, seems not related with paid option

**Comment by janik-cloudflare** [comment] 2022-03-09 16:24
Hi there, closing this as a duplicate of #49.

**Closed by janik-cloudflare** 2022-03-09 16:24 UTC
